spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/edu_link
    username: root
    password: 2004
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
